pinalj/quotes-for-woocommerce

quotes-for-woocommerce/includes/class-email-manager.php, quotes-for-woocommerce/includes/emails/class-qwc-req-new-quote.php, quotes-for-woocommerce/includes/qwc-functions.php, quotes-for-woocommerce/quotes-woocommerce.php, quotes-for-woocommerce/templates/emails/plain/request-new-quote.php.php, quotes-for-woocommerce/templates/emails/plain/send-quote.php, quotes-for-woocommerce/templates/emails/request-new-quote.php, quotes-for-woocommerce/templates/emails/send-quote.php
Merging some fixes into the master
=> Email notifications

quotes-for-woocommerce/includes/emails/class-qwc-req-new-quote.php, quotes-for-woocommerce/includes/emails/class-qwc-send-quote.php
The plugin throws an Internal Server Error at Checkout. The same has
been fixed. Along with that, fixed some warnings displayed in the Quote
Email as well.
=> Internal Server Error at Checkout

quotes-for-woocommerce/uninstall.php
Delete new setting to display prices when plugin is uninstalled
=> Delete new setting when plugin is uninstalled

quotes-for-woocommerce/quotes-woocommerce.php, quotes-for-woocommerce/readme.txt
=> Version 1.4

quotes-for-woocommerce/quotes-woocommerce.php
=> Version updated

quotes-for-woocommerce/uninstall.php
Delete the new settings on uninstall
=> Delete the new settings on uninstall

quotes-for-woocommerce/includes/emails/class-qwc-req-new-quote.php, quotes-for-woocommerce/includes/emails/class-qwc-request-sent.php, quotes-for-woocommerce/includes/emails/class-qwc-send-quote.php, quotes-for-woocommerce/quotes-woocommerce.php, quotes-for-woocommerce/templates/emails/plain/send-quote.php, quotes-for-woocommerce/templates/emails/send-quote.php
=> Fixes 1.6.1

quotes-for-woocommerce/languages/quote-wc.pot, quotes-for-woocommerce/quotes-woocommerce.php
1. Added .pot file for string translations.
2. Added text domain & domain path
=> Multi lingual compatibility

quotes-for-woocommerce/uninstall.php
Add the new setting to be deleted in the uninstall.php for when the
plugin is to be deleted.
=> Add the new setting to uninstall.php

quotes-for-woocommerce/templates/emails/plain/send-quote.php, quotes-for-woocommerce/templates/emails/send-quote.php
Update woocommerce_email_before_order_table hook
=> Update woocommerce_email_before_order_table hook

quotes-for-woocommerce/quotes-woocommerce.php
Fix for the issue "Prices displayed on My Accounts->Orders page"
https://wordpress.org/support/topic/goooood-but/
=> Prices displayed on My Accounts->Orders page

quotes-for-woocommerce/class-quotes-wc.php, quotes-for-woocommerce/quotes-woocommerce.php
=> Full path for include files

quotes-for-woocommerce/assets/css/qwc-frontend.css, quotes-for-woocommerce/assets/css/qwc-shop.css, quotes-for-woocommerce/class-quotes-wc.php
=> CSS changes

class-quotes-wc.php, quotes-woocommerce.php, readme.txt
Updated Version number & tested up to value.
=> Version 1.7.2

class-quotes-wc.php, quotes-woocommerce.php, readme.txt
Updated plugin version number.
=> Version 1.10

class-quotes-wc.php, includes/blocks/class-quotes-wc-blocks-integration.php
1. Emails not being initiated on quote order placement. 2. Quote Status not updated in DB on order placement.
=> WC Blocks compatibility.

assets/css/qwc-wc-checkout-blocks.css, class-quotes-wc.php
Fixed the same by hiding the fields using css.
=> Hide address fields setting does not work with WC Blocks

class-quotes-wc.php, quotes-woocommerce.php, readme.txt
Updated plugin version number and changelog.
=> Version 2.0.1

assets/js/qwc-admin.js, class-quotes-wc.php
Added nonce checks for ajax calls
=> Add nonce checks

quotes-woocommerce.php
Add WC active check. If not found, deactivate the plugin and display an error message to the user.
=> WC active check

class-quotes-wc.php, quotes-woocommerce.php, readme.txt
=> Version 2.0.2

assets/css/qwc-frontend.css, includes/class-quotes-payment-gateway.php
Fixed an issue where price is displayed on the Cart Block
=> Price displayed on Cart Block

class-quotes-wc.php, quotes-woocommerce.php, readme.txt
Add premium version link & update plugin version.
=> Fixes 2.1.1

includes/admin/class-quotes-wc-general-settings.php, includes/qwc-functions.php
Add filters to allow for finer control in the premium version.
=> Add filters

class-quotes-wc.php, languages/quote-wc.pot, quotes-woocommerce.php, readme.txt
Version 2.2 - Updated version number, WC Tested upto value & Changelog.
=> Version 2.2

assets/css/qwc-shop.css
Woodmart theme mini cart amount display fix.
=> Woodmart theme fix

assets/js/vama-dismiss-tracking-notice.js, includes/tracking/class-vama-plugin-tracking.php
Fix bugs found in tracking code.
=> tracking bug fixes

class-quotes-wc.php, includes/class-qwc-data-tracking.php, quotes-woocommerce.php
The activation and deactivation hooks are not being executed when the registration is not in the base file.
=> Activation and deactivation functions not executed

assets/js/qwc-product-page.js, class-quotes-wc.php, includes/class-quotes-payment-gateway.php, readme.txt
HTML tag not closed correctly in readme.txt
=> HTML tag fix

assets/js/qwc-notice.js, changelog.txt, class-quotes-wc.php, includes/admin/class-quotes-product-settings.php, includes/admin/class-quotes-wc-general-settings.php, quotes-woocommerce.php, templates/emails/plain/new-quote-request-sent-customer.php, templates/emails/plain/request-new-quote.php, templates/emails/plain/send-quote.php, templates/emails/send-quote.php, uninstall.php
Updated plugin version to 2.4 and made all code same as WC copy except for tracking data.
=> Version 2.4

class-quotes-wc.php, package.json, uninstall.php
Rectified file version numbers and some minor edits.
=> Minor changes

assets/css/qwc-frontend.css, includes/qwc-functions.php
Compatibility changes with Pro 1.5
=> Compatibility changes

class-quotes-wc.php, includes/blocks/class-quotes-wc-blocks-integration.php, includes/qwc-functions.php
Compatibility fix for new feature of mixed orders in Pro.
=> Added a new filter

includes/class-quotes-payment-gateway.php
See required variables in constructor - https://developer.woocommerce.com/docs/woocommerce-payment-gateway-api/#1-creating-a-basic-payment-gateway
=> Address WooCommerce Payment Gateway API required fields

assets/css/qwc-frontend.css
Remove the css to hide the tfoot on the thank you page for the totals.
=> Remove css

changelog.txt, class-quotes-wc.php, languages/quote-wc.pot, quotes-woocommerce.php, readme.txt, templates/emails/plain/request-new-quote.php, templates/emails/plain/send-quote.php, templates/emails/request-new-quote.php
Version 2.6 & fixed some warnings displayed during .pot generation.
=> Version 2.6

quotes-woocommerce.php
Added requires woocommerce tag to avoid errors and deactivation.
=> Added file tag

changelog.txt, class-quotes-wc.php, languages/quote-wc.pot, quotes-woocommerce.php, readme.txt
Updated .pot, changelog, plugin version and tested up to version numbers.
=> Version 2.7

includes/emails/class-qwc-request-new-quote.php, includes/emails/class-qwc-request-sent.php, includes/emails/class-qwc-send-quote.php, templates/emails/plain/new-quote-request-sent-customer.php, templates/emails/plain/request-new-quote.php, templates/emails/plain/send-quote.php, templates/emails/request-new-quote.php, templates/emails/send-quote.php
fixed spacing to appease the linter.
=> PHPCS compliance

assets/css/qwc-frontend.css, templates/emails/request-new-quote.php
Modify the admin order url link display for a cleaner UX.
=> Fix link display

changelog.txt, class-quotes-wc.php, languages/quote-wc.pot, quotes-woocommerce.php, readme.txt
Updated .pot, plugin version and changelog.
=> Version 2.8

class-quotes-wc.php
Add order object checks in the code to ensure no warnings/errors are generated.
=> Add order object checks

templates/emails/plain/new-quote-request-sent-customer.php, templates/emails/plain/request-new-quote.php
=> Fixed Functions in two files
